centreon/centreon-engine

doc/release_notes/engine18.rst, src/configuration/applier/globals.cc, src/configuration/applier/logging.cc
=> fix(configuration): use Centreon Web-compatible values for /debug_level/

doc/conf.py, doc/installation/index.rst
Add instructions to use the new repository adn update instructions to install packages.
Tested installation based on documentation.
- Centos 6
- Centos 7
- Debian Jessie
- Debian Stretch
- Ubuntu 14.04
- Ubuntu 16.04
=> update content with new repository and CentOS7

build/CMakeLists.txt
=> chore(build): update version to 19.04.1.

doc/installation/index.rst
Update documentation to support 19.04 version
=> Update documentation 19.04 version

inc/com/centreon/engine/host.hh, src/config.cc, src/host.cc, src/service.cc
Add some missing resolve and fix compilation warnings
=>  enh(config): add some missing resolve and fix compilation warnings

src/configuration/applier/command.cc
Lookup for connectors in connector list and not in command list...
=> fix(command): lookup for connectors in connector list

inc/com/centreon/engine/service.hh, src/checks/checker.cc, src/commands/command.cc, src/commands/raw.cc, src/config.cc, src/configuration/applier/host.cc, src/configuration/object.cc, src/retention/dump.cc, src/service.cc, tests/commands/simple-command.cc, tests/configuration/applier/applier-service.cc
=> fix(host): memory leaks fixed

inc/com/centreon/engine/host.hh, src/host.cc, src/service.cc
Remove some bad std::string(nullptr) constructs.
=> fix(host,service): Remove some bad std::string(nullptr) constructs.

inc/com/centreon/engine/contact.hh, inc/com/centreon/engine/contactgroup.hh, inc/com/centreon/engine/flapping.hh, inc/com/centreon/engine/host.hh, inc/com/centreon/engine/hostgroup.hh, inc/com/centreon/engine/service.hh, inc/com/centreon/engine/servicegroup.hh, modules/external_commands/inc/com/centreon/engine/modules/external_commands/commands.hh, modules/external_commands/inc/com/centreon/engine/modules/external_commands/processing.hh, modules/external_commands/src/commands.cc, modules/external_commands/src/processing.cc, src/checks/checker.cc, src/config.cc, src/configuration/applier/contactgroup.cc, src/configuration/applier/host.cc, src/configuration/applier/hostgroup.cc, src/configuration/applier/servicegroup.cc, src/contact.cc, src/contactgroup.cc, src/host.cc, src/macros.cc, src/macros/grab_host.cc, src/macros/grab_service.cc, src/macros/grab_value.cc, src/service.cc, tests/configuration/applier/applier-service.cc, tests/notifications/host_normal_notification.cc
reference object by string to avoid some leaks
=> fix(contactgroup): reference object by string to avoid some leaks

src/notifier.cc, tests/notifications/service_normal_notification.cc
Normal notification filter reviewed.
=> fix(notifier): Normal notif with interval=0

src/configuration/applier/service.cc, src/notifier.cc, src/utils.cc, tests/configuration/applier/applier-service.cc
Segfaul in notifiers contactgroups is fixed.
=> fix(notifier): contactgroups resolution was not correct.

src/configuration/applier/contact.cc
A little fix on notification commands.
=> fix(contact): notification commands were not cleaned up

inc/com/centreon/engine/checks/checker.hh, inc/com/centreon/engine/notifier.hh, src/notifier.cc
first delay notification and last recovery delay fixed.
=> fix(notifier): first_delay and recovery delay notifications reviewed.

inc/com/centreon/engine/configuration/host.hh, inc/com/centreon/engine/configuration/service.hh, src/configuration/host.cc, src/configuration/service.cc
These fields will not be supported in 20.04
=> fix(conf): add a warning for deprecated field.

src/configuration/applier/hostescalation.cc, src/configuration/applier/serviceescalation.cc
Crashes in remove_object fixed.
=> fix(escalation): Crash fixed on escalation remove.

build/cmake.sh, inc/com/centreon/engine/configuration/applier/hostgroup.hh, inc/com/centreon/engine/configuration/hostgroup.hh, src/configuration/applier/hostgroup.cc, src/configuration/hostgroup.cc, src/configuration/parser.cc, src/configuration/service.cc, src/configuration/state.cc, src/hostgroup.cc
A fix in the reload involving hostgroups.
=> fix(applier/hostgroup): Bad loop and others things

tests/configuration/applier/applier-contact.cc, tests/configuration/applier/applier-contactgroup.cc, tests/configuration/contact.cc, tests/contacts/contactgroup-config.cc, tests/contacts/simple-contactgroup.cc
remove includes that does not exist anymore and that break the build
=> fix(tests): com/centreon/shared_ptr.hh does not exist anymore.

src/macros/grab_host.cc, src/macros/grab_service.cc, src/macros/grab_value.cc, tests/configuration/applier/applier-command.cc
fix contact and contactgroup macro expand
=> fix(contact): macros where not expanded for contact and contactgroup

doc/release_notes/engine19.10.rst, doc/release_notes/index.rst
=> enh(doc): add release notes for 19.10

CMakeLists.txt, cmake.sh, inc/com/centreon/engine/macros/grab_value.hh, src/commands/raw.cc, src/macros/grab_value.cc, tests/CMakeLists.txt
Here is the fix linked to #269 issue.
=> Mon 4357 null string

src/macros.cc, src/notifier.cc
=> fix(macros): fix bad iterators

inc/com/centreon/engine/macros/grab_value.hh, modules/external_commands/src/commands.cc, src/commands/raw.cc, src/configuration/applier/contact.cc, src/configuration/applier/service.cc, src/configuration/contact.cc, src/configuration/host.cc, src/configuration/service.cc, src/contact.cc, src/host.cc, src/macros.cc, src/macros/grab_value.cc, src/macros/process.cc, src/retention/applier/contact.cc, src/retention/applier/host.cc, src/retention/applier/service.cc, src/retention/contact.cc, src/retention/dump.cc, src/retention/host.cc, src/retention/service.cc, src/service.cc, src/xsddefault.cc, tests/configuration/applier/applier-contact.cc
Fix various custom_variables bugs.
=> fix(custom_var): fix various cv bugs.

inc/com/centreon/engine/commands/command.hh, inc/com/centreon/engine/commands/connector.hh, inc/com/centreon/engine/commands/environment.hh, inc/com/centreon/engine/commands/forward.hh, src/commands/connector.cc, src/commands/environment.cc, src/commands/forward.cc
=> enh(connector): fix arm compile.

doc/release_notes/engine19.10.rst, inc/com/centreon/engine/configuration/state.hh, src/configuration/state.cc
Service configuration lookup fixed.
=> fix(configuration/service): Bug fixed in service configurations lookup

.gitignore, doc/release_notes/engine19.10.rst, src/configuration/applier/contact.cc, src/configuration/applier/host.cc, src/configuration/applier/service.cc, src/notifier.cc, tests/configuration/applier/applier-contactgroup.cc, tests/configuration/applier/applier-hostgroup.cc, tests/configuration/applier/applier-servicegroup.cc, tests/notifications/service_normal_notification.cc
port of several patches made in 19.10.x
=> 19.10 port

src/notifier.cc, tests/notifications/host_recovery_notification.cc
Regression on recovery notification fixed.
=> fix(notifier): Regression in condition on recovery

src/notifier.cc, tests/notifications/host_recovery_notification.cc
Regression on recovery notification fixed.
=> fix(notifier): Regression on recovery notification fixed.

doc/release_notes/engine19.10.rst, src/host.cc, src/service.cc
=> Mon 4557 double recovery 20.04

doc/release_notes/engine19.10.rst, src/host.cc, src/service.cc
Double recovery notification fixed.
=> fix(notifier): On recovery, two notifications could be sent

src/downtimes/host_downtime.cc, src/downtimes/service_downtime.cc
A port of the equivalent fix for 19.10.x
=> fix(downtime): regression on downtime end time fixed

src/objects/downtime.cc
an overflow can occurs in dt scheduling.
It should pass 19.04.X Acceptance test
=> enh(downtime): fix a possible overflow for dt->end_time.

src/downtimes/host_downtime.cc, src/downtimes/service_downtime.cc
For reccurent DT an overflow can occurs, and there will be now scheluded DT.
Scheduling a recurrent DT and check if it works for broker.
=> fix(dt): some overflow can occurs

src/notifier.cc
Just a cleanup to remove a double implementation.
=> fix(notifier): No notification on recovery was buggish

src/utils.cc
Segfault fixed in engine when it receives a SIGTERM.
=> fix(utils): Segfault fixed on SIGTERM signal.

src/utils.cc
This is a fix so that engine does not crash when it receives a SIGTERM.
=> Mon 4582 segfault engine

modules/bench/passive/main.cc
remove use of clib singleton in bench
if build works, the job is done.
=> enh(bench): remove clib singleton.

doc/release_notes/engine20.04.rst, doc/user/configuration/basics/standard_macros.rst, inc/com/centreon/engine/configuration/state.hh, inc/com/centreon/engine/macros/defines.hh, src/configuration/applier/macros.cc, src/configuration/state.cc, src/macros.cc, src/macros/grab_value.cc, tests/configuration/applier/applier-global.cc, tests/macros/macro.cc
add poller_id field to fill POLLERID macro
**Fixes** #4772
use a customvar with POLLER_ID and add a poller_id=X in your centengine.cfg (where x is a numerical value)
=> feat(config): add poller_id field to fill POLLERID macro

doc/release_notes/engine19.10.rst, src/checks/checker.cc, src/downtimes/downtime_manager.cc, src/downtimes/service_downtime.cc, src/host.cc, src/retention/dump.cc, src/service.cc, tests/CMakeLists.txt, tests/checks/service_check.cc, tests/checks/service_retention.cc
When downtimes are removed, the first downtime of the list could be
removed by mistake.
When downtimes are removed, the first one in the list could be also removed.
=> fix(downtime_manager): Log functions added and a fix in dt removals

doc/release_notes/engine19.10.rst, src/checks/checker.cc, src/downtimes/downtime_manager.cc, src/downtimes/service_downtime.cc, src/host.cc, src/retention/dump.cc, src/service.cc, tests/CMakeLists.txt, tests/checks/service_check.cc, tests/checks/service_retention.cc, tests/commands/simple-command.cc
* Hard/Soft type fixed
* Singletons instanciations
* Service output with long output.
Port of various modifications already made in 19.10.x
=> enh(various): Port of modifications in 19.10

doc/release_notes/engine19.10.rst, doc/release_notes/engine20.04.rst, src/notifier.cc, tests/enginerpc/client.cc, tests/notifications/service_normal_notification.cc
See MON-4996-volatile-downtime description.
=> Mon 4996 volatile downtime 20.04

src/checks.cc
Hard/Soft durations should be better computed.
=> fix(checks): fix on Hard/Soft durations

CMakeLists.txt, Jenkinsfile, conanfile.txt, enginerpc/CMakeLists.txt, tests/CMakeLists.txt
add support for conan dependency manager. 
=> add support for conan dependency manager. 

CMakeLists.txt, enginerpc/CMakeLists.txt, enginerpc/engine.proto, inc/com/centreon/engine/shared.hh, modules/external_commands/CMakeLists.txt, tests/CMakeLists.txt, tests/enginerpc/client.cc, tests/timeperiod/utils.cc
add reflection and a namespace for engine rpc. 
fix some ut compile on recent linux.
using grpc_curl
=> enh(grpc): add reflection and a namespace for engine rpc.

src/service.cc, tests/checks/service_check.cc
Service checks tests were polluted by host checks launched in background.
Execute unit tests 30 times.
=> fix(tests): service checks tests were polluted by host checks

inc/com/centreon/engine/configuration/state.hh, src/configuration/state.cc, src/main.cc, tests/configuration/applier/applier-global.cc, tests/enginerpc/client.cc, tests/enginerpc/enginerpc.cc
Load grpc on port provided by rpc_id in centengine.cfg. If not 51000 + broker_id.
check that grpc is binding on the grpc port present in centengine.cfg.
=> Grpc set port

src/macros.cc, src/shared.cc
Macros about time were badly replaced.
=> fix(macro): Several macros not replaced.

README.md
=> doc(README.md): compilation instructions

cmake.sh
=> fix(cmake.sh): pip3 install conan

scripts/centengine.service.in
Hi,
This is a simple backport of #172 (9ac929a) into 19.10.x branch.
As already done with https://github.com/centreon/centreon-broker/pull/221.
Thx !
=> Backport #172 (9ac929a) into 19.10.x

src/macros/grab_value.cc
=> Mon 5814 segfault on demand macros

src/globals.cc, src/host.cc, src/service.cc, tests/macros/macro.cc
problem & current id was equal
=> Mon 5898 problem

tests/checks/anomalydetection.cc
We simulate some time change, in the same time, we wait for some
duration, and the software executes several threads... :-(
Fix some unit tests.
=> fix(test): always the same random behavior.

.github/PULL_REQUEST_TEMPLATE.md
- Update the PULL_REQUEST_TEMPLATE 
- Remove unsupported versions
- Add new maintenance branch
=> enh(PULL_REQUEST_TEMPLATE): deprecate old versions and update

src/service.cc, tests/checks/service_check.cc
=> fix(notification): stalking option not working as intended

Jenkinsfile
trigger properly centreon-web job
=> chore(build): trigger properly centreon-web job

enginerpc/examples/init-proto.sh, enginerpc/examples/service_check.py, inc/com/centreon/engine/customvariable.hh, src/configuration/applier/host.cc, src/statusdata.cc
There was a regression on customvariables filtering. It is fixed now.
=> Mon 6351 cv filter

doc/en/release_notes/engine20.04.rst, src/macros.cc, tests/macros/macro.cc
=> Mon 6507 timet macro displays 20.04

doc/en/release_notes/engine20.10.rst, src/macros.cc, tests/macros/macro.cc
=> Mon 6507 timet macro displays 20.10

doc/en/release_notes/engine19.10.rst, src/macros.cc, tests/macros/macro.cc
=> Mon 6507 timet macro displays 19.10

conanfile.txt, inc/com/centreon/engine/configuration/state.hh, inc/com/centreon/engine/globals.hh, inc/com/centreon/engine/notifier.hh, src/configuration/applier/globals.cc, src/configuration/applier/state.cc, src/configuration/state.cc, src/contact.cc, src/globals.cc, src/notifier.cc, tests/CMakeLists.txt, tests/notifications/service_normal_notification.cc, tests/notifications/service_timeperiod_notification.cc
=> Mon 5066 notifications are not sent

src/service.cc
=> fix(flapping) Flapping is not detected

inc/com/centreon/engine/nebstructs.hh, src/broker.cc, src/service.cc, tests/notifications/service_flapping_notification.cc
=> Mon 6170 flapping not detected

README.md, cmake.sh, modules/bench/passive/main.cc, modules/external_commands/src/commands.cc, src/commands/connector.cc, src/commands/raw.cc, tests/notifications/service_normal_notification.cc
Changes in engine because of changes in the clib.
REFS: MON-5939
=> fix(clib): process api changed

doc/en/release_notes/engine20.04.rst, src/contact.cc, src/notification.cc, src/notifier.cc, src/timeperiod.cc, tests/CMakeLists.txt, tests/macros/macro.cc, tests/notifications/service_timeperiod_notification.cc, tests/timeperiod/get_next_valid_time/calendar_date.cc
=> Mon 6538 user time period not respected 20.04

src/notifier.cc, tests/notifications/host_downtime_notification.cc
=> fix(notification): Notify RECOVERY when exiting downtime

README.md
=> enh(project): enhance root readme

CHANGELOG.md, src/macros.cc, src/macros/grab_host.cc, src/macros/grab_service.cc, src/macros/grab_value.cc, tests/macros/macro.cc, tests/macros/macro_hostname.cc, tests/macros/macro_service.cc
=> fix(macro):  macro doesn't appear in notifications

src/checks/checker.cc, src/configuration/applier/globals.cc, src/configuration/applier/state.cc, src/configuration/state.cc, src/globals.cc, src/host.cc, src/service.cc
Deletes and prevents from use_aggressive_host_checking in configuration (centengine.cfg).
=> enh(configuration): delete use_aggressive-host_cheking

inc/com/centreon/engine/configuration/state.hh, src/checks/checker.cc, src/configuration/state.cc, src/host.cc, src/service.cc
Several attributes were still there but not used. And so on for comments.
=> enh(use_aggressive_host_checking): This option is no more used.

src/macros.cc, src/macros/grab_host.cc, src/macros/grab_service.cc, src/macros/grab_value.cc, tests/macros/macro.cc
=> fix(macro): macro doesn't appear in notifications

src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> fix (downtime): Limit downtime start date, end date and duration

CHANGELOG.md, src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> Mon 6764 limit downtime date 20.10

CHANGELOG.md, src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> Mon 6764 limit downtime date 20.04

doc/en/release_notes/engine19.10.rst
=> enh(release): prepare 19.10.17 release note

CMakeLists.txt, cmake.sh, conanfile.txt, enginerpc/CMakeLists.txt, inc/com/centreon/engine/anomalydetection.hh, inc/com/centreon/engine/opt.hh, inc/com/centreon/engine/retention/host.hh, inc/com/centreon/engine/retention/object.hh, inc/com/centreon/engine/retention/service.hh, src/anomalydetection.cc, src/retention/host.cc, src/retention/service.cc, tests/CMakeLists.txt, tests/configuration/applier/applier-service.cc, tests/retention/service.cc
json11 changed to nlohmann_json
dependencies upgraded to be able to use them from the conan-center.
=> Using conan center

inc/com/centreon/engine/timeperiod.hh, src/contact.cc, src/host.cc, src/notifier.cc, src/timeperiod.cc, tests/macros/macro.cc
=>  fix(check): Engine burns 100% of the CPU with check_period set to none

CMakeLists.txt, README.md, tests/downtimes/downtime_finder.cc
=> Mon 7395 compilation arm

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, tests/downtimes/downtime_finder.cc
=> Mon 7395 compilation arm 21.04

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, tests/downtimes/downtime_finder.cc
=> Mon 7395 compilation arm 20.10

CHANGELOG.md, CMakeLists.txt, README.md, cmake.sh, tests/downtimes/downtime_finder.cc
=> Mon 7395 compilation arm 20.04

Jenkinsfile
=> fix(ci):quality gate timeout management

Jenkinsfile
Adjusting quality gate sleeping for C++ sonar "analysis"
=> fix sleeping on qg wait

CHANGELOG.md, deps.sh, enginerpc/enginerpc.cc, inc/com/centreon/engine/common.hh, inc/com/centreon/engine/enginerpc.hh, inc/com/centreon/engine/globals.hh, modules/external_commands/inc/com/centreon/engine/modules/external_commands/utils.hh, modules/external_commands/src/utils.cc, src/globals.cc, tests/enginerpc/enginerpc.cc
=> fix(various): centengine segfaults when it is terminated.

inc/com/centreon/engine/commands/connector.hh, inc/com/centreon/engine/logging/broker.hh, src/commands/connector.cc, src/logging/broker.cc, src/nebmods.cc
Possible deadlock removed in logs production.
REFS: MON-10885
=> Mon 10885 log deadlock

enginerpc/examples/README-gRPC.md
=> chore(README): update grpc readme

enginerpc/examples/engine-rpc-client.py
=> Mon 7028 lack of logs

enginerpc/examples/engine-rpc-client.py
=> MON-7028-lack-of-logs

CHANGELOG.md, src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> Mon 10693 limit end date downtime

CHANGELOG.md, src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> Mon 10693 limit end date downtime 20.10

CHANGELOG.md, src/downtimes/downtime_manager.cc, tests/downtimes/downtime_finder.cc
=> Mon 10693 limit end date downtime 20.04

cmake.sh
Add support to use cmake.sh with Ubuntu.
Tested with Ubuntu 20.04 (LTS) and 21.04
=> add support to use with Ubuntu

CHANGELOG.md, src/service.cc
=> Mon 10642 notif soft down host 21.04

CHANGELOG.md, src/service.cc
=> Mon 10642 notif soft down host 20.10

Jenkinsfile
Fix some ci things like stashing and variable names
=> fix(ci): fix rpm stashing

src/service.cc
=> fix(notification): notification is only send if the host is on state_up

enginerpc/engine.proto, enginerpc/engine_impl.cc, inc/com/centreon/engine/command_manager.hh
=> Mon 7024 create log grpc

CHANGELOG.md, inc/com/centreon/engine/notification.hh, src/notification.cc, src/notifier.cc, src/retention/dump.cc, tests/notifications/service_normal_notification.cc
=> Mon 7388 recovery notif for all user 20.10

CHANGELOG.md, inc/com/centreon/engine/notification.hh, src/notification.cc, src/notifier.cc, src/retention/dump.cc, tests/notifications/service_normal_notification.cc
=> Mon 7388 recovery notif for all user 21.04

src/anomalydetection.cc, tests/checks/anomalydetection.cc
=> fix (anomalydetection): Add unit to anomaly thresholds curves

CHANGELOG.md, src/anomalydetection.cc, tests/checks/anomalydetection.cc
=> Mon 10959 add unit to anomaly thresholds 21.04

CHANGELOG.md, src/anomalydetection.cc, tests/checks/anomalydetection.cc
=> Mon 10959 add unit to anomaly thresholds 20.10

src/host.cc, src/service.cc, tests/notifications/host_flapping_notification.cc, tests/notifications/service_flapping_notification.cc
=> fix(flapping): start flapping on not OK state

Jenkinsfile
=> fix(build): deactivate packaging debian 10
