doc/release_notes/engine18.rst, src/commands/raw.cc
Unlike was the documentation told, environment macros were not properly generated and remained empty. This is now fixed and only summary macros are not generated when using large installation tweaks (as per documentation).
=> fix(macros): generate environment macros when using large installation tweaks

doc/exploit/running.rst
It's not engine.cfg but centengine.cfg, moreover engine.cfg doesn't exist for me and i've got the last version of centreon in iso on a Virtualbix VM
=> mistake at line 18, there was wrote engine.cfg

src/configuration/host.cc, src/configuration/service.cc
=> Make recovery_notification_delay inheritable.

src/configuration/applier/contact.cc, src/configuration/applier/host.cc
host and contact custom macro are not inserted into centreon_storage db anymore.
This changeset fix this issue.
=> fix(customvalues): send host and contact cv to broker

src/configuration/applier/host.cc, src/configuration/applier/service.cc
This patch is not suffisent but already solves ourselves from an exception during a reload.
=> fix(applier): std::string cannot be initialized from nullptr

scripts/centengine.service.in
Hi,
This PR closes https://github.com/centreon/centreon/issues/7631
As explained there, could be interesting to start engine after cbd, as it is the expected order.
Similar to https://github.com/centreon/centreon-broker/pull/221.
Thank you :+1:
Edit : issue still present in 19.10.1.
=> Start engine after cbd

modules/external_commands/src/commands.cc, tests/external_commands/host.cc, tests/external_commands/service.cc
When a host was specified in an external command from its ip,
the lookup could lead to a crash.
=> fix(external_commands): Segfault fixed in host lookup.

src/broker.cc, src/daterange.cc, src/dependency.cc, src/hostdependency.cc, src/retention/host.cc, src/retention/object.cc, src/retention/parser.cc, src/retention/service.cc, src/retention/state.cc, src/timerange.cc
To compile the code in a FreeBSD environment, creating a system compatible and clang compatible port, I needed to add these headers to some code.
with these changes, I have the engine successfully compiled on FreeBSD 12 and with clang
The output is:
```
centengine: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.0 (1200086), FreeBSD-style,
with debug_info, not stripped
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```
The lab with FreeBSD ports functional:
https://github.com/freebsd-centreon/ports/tree/master/centreon-engine
=> Add header changes to permit compile in clang/freebsd

doc/release_notes/engine19.04.rst, src/objects/downtime.cc
Fix concerning to fixed downtimes one just after the other.
When the first one is stopped and just before the second to start, it was possible to receive notifications of devices in downtime.
=> fix(downtime): Notification problem between two downtimes fixed.

doc/release_notes/engine19.10.rst, src/notifier.cc, tests/notifications/service_normal_notification.cc
Here is a fix on normal notifications.
A device is in warning hard => notification
The device changes to critical hard => notification (that was not the case)
The device changes again to warning hard => notification (that was not the case)
That should fix #294
=> fix(notifier): Double notification could fail

doc/release_notes/engine19.10.rst, src/notifier.cc, tests/notifications/service_normal_notification.cc
When a service is configured with a first delay notification but without recovery notification, the first delay notification does not work as expected.
=> Mon 4554 first notif delay no recovery

doc/release_notes/engine19.10.rst, src/notifier.cc, tests/notifications/service_normal_notification.cc
This is the backport of the fix in branch MON-4554 over the master branch.
=> fix(notifier): No first notification delay if no recovery notif

src/objects/downtime.cc
If end_time == LongLong::max() then end_time + 1 < 0 which is the bug.
This case appears when a downtime is sent from broker on a BA.
You can program a downtime with an end_time == LongLong::max()
such this one : SCHEDULE_SVC_DOWNTIME;_Module_BAM_1;ba_1;1575373885;9223372036854775807;1;0;0;Centreon Broker BAM
You may notice the value of the end_time that is very big!
Otherwise, run the TA, if they pass, it is good!
=> fix(downtime): Regression on downtime fixed.

doc/release_notes/engine19.10.rst, src/notifier.cc, tests/notifications/service_normal_notification.cc
Configure a volatile passive service with notifications sent to a user.
When the service is set to the critical state, it notifies.
When the service is set to the warning state, it notifies.
Now disable notifications on this service.
When the service is set to the critical state, it should **not** notify. This patch fixes this point.
The *procedure* is given in the description.
=> Fix notification volatile 20.04

doc/release_notes/engine19.10.rst, inc/com/centreon/engine/notifier.hh, inc/com/centreon/engine/retention/host.hh, src/notifier.cc, src/retention/host.cc, src/service.cc, tests/notifications/service_normal_notification.cc
If a service is in critical state and has its recovery notification flag enabled. If we acknowledge it, when it will go back to OK state, a recovery notification will be sent: this is the required behaviour.
MON-4594
=> fix(notifier): Recovery are sent even if service is acknowledged.

doc/release_notes/engine19.10.rst, modules/external_commands/src/commands.cc, tests/CMakeLists.txt, tests/custom_vars/extcmd.cc
A bug was introduced on 19.10 for the extcmd CHANGE_CUSTOM_X_VAR. When
we were updating a custom variable with a command, the updated value
was always empty string.
**Fixes** #4616
try a CHANGE_CUSTOM_HOST_VAR extcmd and a CHANGE_CUSTOM_SVC_VAR extcmd
=> fix(extcmd): fix a 19.10 regression in CHANGE_CUSTOM_X_VAR

src/customvariable.cc
Little fix, so that a macro, when constructed, has its modified flag set to false.
Tests can be done as explained by Colin.
=> fix(customvariable): modified is set to false in the constructor

cmake.sh, doc/release_notes/engine19.10.rst, src/configuration/applier/service.cc, src/service.cc, tests/configuration/applier/applier-service.cc
Configure a service with all the notification flags enabled and no stalk flags.
Push the configuration. Then modify the service to change a little thing (not the notification or stalk flags).
Push again the configuration. If the bug is there, you should see in the centreon_storage that stalk
flags are not all set to 0. If the bug is fixed, you should see all the stalk flags set to 0.
With the patched version, you should also test the same steps but with only the unknown flag enabled …
=> Mon 4719 stalk options changed on modification

src/retention/parser.cc, src/string.cc, tests/CMakeLists.txt, tests/string/string.cc
When the retention is read, values could be split. This fixed by this patch.
=> fix(retention/parser): perfdata truncated when retention read.

doc/release_notes/engine19.10.rst, src/retention/parser.cc, src/string.cc, tests/CMakeLists.txt, tests/string/string.cc
When engine was restarted, perfdata were get back from the retention.dat file. And when they were read, they were split at the first ';' character encountered. The impact was perfdata were badly written in the centreon_storage database.
=> fix(retention): parser could truncate values.

src/service.cc, tests/CMakeLists.txt, tests/checks/service_check.cc, tests/commands/simple-command.cc
Hard and Soft states are not always coherent. This was due to a bad code in the service::handle_async_check_result() method.
Several tests have been added to match use cases, but maybe we do not cover all of them.
You must know all the stories about soft and hard state types and test them.
=> Mon 4058 hard soft duration

modules/external_commands/src/commands.cc, src/downtimes/downtime_manager.cc
Create 100 downtimes on 100 hosts.
Remove 20 of them before they start.
When they should start, you should see 80 downtimes.
=> fix(downtimes): downtime deletions was a little crazy

doc/release_notes/engine19.10.rst, src/macros/grab_value.cc, tests/CMakeLists.txt, tests/external_commands/service.cc, tests/macros/macro.cc
fix TOTALXXXX macros
TOTALSERVICESOK TOTALSERVICESWARNING TOTALSERVICESCRITICAL ... were not working, they were replaced by empty values.
create a command with an $TOTALSERVICESOK$ macro. this macro should be replaced by a numerical value
=> fix(macro): fix TOTALXXXX macros (19.10)

doc/release_notes/engine19.10.rst, src/macros/grab_value.cc, tests/macros/macro.cc
fix TOTALXXXX macros
TOTALSERVICESOK TOTALSERVICESWARNING TOTALSERVICESCRITICAL ... were not working, they were replaced by empty values.
create a command with an $TOTALSERVICESOK$ macro. this macro should be replaced by a numerical value
=> fix(macro): fix TOTALXXXX macros

inc/com/centreon/engine/common.hh, inc/com/centreon/engine/downtimes/downtime.hh, inc/com/centreon/engine/downtimes/downtime_manager.hh, inc/com/centreon/engine/events/timed_event.hh, modules/external_commands/src/commands.cc, src/downtimes/downtime.cc, src/downtimes/downtime_finder.cc, src/downtimes/downtime_manager.cc, src/downtimes/host_downtime.cc, src/downtimes/service_downtime.cc, src/events/timed_event.cc, src/retention/applier/downtime.cc
Add 100 downtimes on 100 hosts
Remove 20 of them.
Wait for them to start all.
Verify there are exactly 80 downtimes running.
=> fix(downtime): Bad recursive way in downtimes deletions

doc/release_notes/engine19.10.rst, inc/com/centreon/engine/common.hh, inc/com/centreon/engine/downtimes/downtime.hh, inc/com/centreon/engine/downtimes/downtime_manager.hh, inc/com/centreon/engine/events/loop.hh, inc/com/centreon/engine/events/timed_event.hh, modules/external_commands/src/commands.cc, src/downtimes/downtime.cc, src/downtimes/downtime_finder.cc, src/downtimes/downtime_manager.cc, src/downtimes/host_downtime.cc, src/downtimes/service_downtime.cc, src/events/loop.cc, src/retention/applier/downtime.cc
When downtimes were removed, there were some memory issues and downtimes were badly removed. This is fixed with this patch.
Create 100 hosts. Apply on each of them one downtime. All the downtimes have to start at the same time. Then, before they all start, remove 20 of them.
When it is time, you should have exactly 80 downtimes that start.
=> fix(downtime): Removing downtimes produced memory issues

CMakeLists.txt, inc/com/centreon/engine/checks/checker.hh, inc/com/centreon/engine/configuration/applier/scheduler.hh, inc/com/centreon/engine/events/timed_event.hh, inc/com/centreon/engine/host.hh, inc/com/centreon/engine/service.hh, src/checks/checker.cc, src/configuration/applier/host.cc, src/configuration/applier/scheduler.cc, src/configuration/applier/service.cc, src/configuration/applier/state.cc, src/host.cc, src/service.cc
Some time ago, we changed how singletons are started. No more load() methods.
There was an impact on the scheduler because it initializes the schedule info when it is created whereas the schedule info is already initialized...
This fix does the job. A new one will come with the anomalydetection :smile: that will be better.
When the bug is there, the scheduler is going mad. If you configure engine with 2000 services,
you can see in the status.dat file many services (almost all) with a very big latency.
Fix the bug and latencies become numbers near of zero.
=> Scheduler regression

doc/release_notes/engine20.04.rst, src/commands/connector.cc
Same PR as MON-4969-timeout adapted to the master branch.
=> fix(connector): timestamp is in milliseconds now.

doc/release_notes/engine19.10.rst, src/notifier.cc, tests/notifications/service_normal_notification.cc
There is a bug in Engine 19.10.x: When a service is volatile, configured to send notifications on critical, warning, recovery states, it sends notifications on those states even if it is in downtime.
This is wrong, in downtime notifications should not be sent.
=> fix(notifier): A volatile service should not be notified when in dt

inc/com/centreon/engine/check_result.hh, modules/external_commands/src/commands.cc, src/anomalydetection.cc, src/check_result.cc, src/checks/checker.cc, src/command_manager.cc, src/host.cc, src/service.cc, tests/notifications/service_flapping_notification.cc
Check_results are faster now. Each time we need to access service or hosts attached to a check_result we have a direct access and don't have anymore to query to the global table.
- [X Patch fixing an issue (non-breaking change)
=> Fix check result lookup

src/configuration/applier/scheduler.cc, src/configuration/applier/state.cc
When a new anomalydetection is created and the configuration is just *reloaded*, the new anomalydetection was not loaded by the scheduler.
Centreon-engine / Centreon-broker are running correctly.
Create a new anomalydetection.
Reload Centreon-Engine and the new anomalydetection should be loaded.
=> Schedule ad

src/anomalydetection.cc, tests/checks/anomalydetection.cc, tests/enginerpc/enginerpc.cc, tests/external_commands/anomalydetection.cc
In centreon engine and broker, service_id and host_id are integers. But thresholds files we get for anomalydetections do not respect this logic. So here is a patch to read strings and convert them to uint.
Let's hope we will understand thresholds files now.
=> Ad id not integers

src/anomalydetection.cc, src/string.cc, tests/checks/anomalydetection.cc
For an anomalydetection, in case of a metric with min/max. New upper and lower thresholds did not contain them. The impact was that their curves were not aligned in centreon-web. Now if min/max are given for the metric, they are kept into their thresholds.
Create an anomalydetection from a metric with min/max.
And take care to the lower and upper thresholds of the anomalydetection. They should contain min/max values.
=> enh(anomalydetection): min/max are kept for upper and lower thresholds.

src/string.cc, tests/string/string.cc
The utf-8 validation was not sufficiently strict.
An error was present in the utf-8 checker. So when a string was not utf-8 encoded, it could be seen as an UTF-8 string.
A new unit test has been added to check this new algorithm.
=> fix(string): utf-8 validator had a bug

inc/com/centreon/engine/configuration/state.hh, inc/com/centreon/engine/globals.hh, src/configuration/applier/globals.cc, src/configuration/applier/state.cc, src/configuration/state.cc, src/globals.cc, src/statusdata.cc
There is a minimal delay now between two instance updates. This delay is instance_heartbeat_interval, it is an integer value representing seconds.
It may be configured in centengine.cfg. Its default value is 30.
=> enh(statusdata): There is a minimal delay now between two instance updates

CMakeLists.txt, cmake.sh, conanfile.txt
Since gcc 5, we can use the new c++ abi. This patch allows use to do so.
The cmake.sh then compiles engine on Debian and Centos8 with this new abi, whereas it does not for Centos8 (gcc 4.8).
=> Let's use the new c++ abi when available

src/macros.cc, tests/macros/macro.cc
fix(macro): the standard macro $TIMET$ now return time in a unix epoch format.
=> MON 6507 $TIMET$ macro displays time instead of epoch

src/contact.cc, src/notification.cc, src/notifier.cc, src/timeperiod.cc, tests/CMakeLists.txt, tests/macros/macro.cc, tests/notifications/service_timeperiod_notification.cc, tests/timeperiod/get_next_valid_time/calendar_date.cc
* fix(notification) the timeperiod are now filtered for the contact
REFS: MON-6538
=> Mon 6538 Engine doesn't respect user's defined notification periods

CHANGELOG.md, src/retention/host.cc, src/retention/service.cc
If the retention.dat file contains date in the future for last_time_... values, they are replaced by the current time which has more
sense. This avoids also to send broker too big timestamps impossible to insert in database.
REFS: MON-6916
=> Mon 6916 last time in the future 20.10

src/events/loop.cc
Here is a fix because of gcc-4.8.5 (the one in centos7). Engine can wait forever in several cases.
REFS: MON-7215
=> fix(loop): sleep_until replaced by sleep_for because of gc 4.8.5

CHANGELOG.md, CMakeLists.txt, src/service.cc
External command of service check result and service status received twice :sob: 
REFS: MON-7351
=> Mon 7351 fix ext cmd 21.04

scripts/logrotate_systemd.conf.in, scripts/logrotate_sysv.conf.in, scripts/logrotate_upstart.conf.in
Logrotate will now create the old dir (archives) directory so that it could be OK.
Launch logrotate and see it work's !
=> [logrotate] add directive for old dir creation

Jenkinsfile
sleep 2 minutes in order to wait for the quality gate status
=> fix(ci): sonar qg timeout management

CHANGELOG.md, CMakeLists.txt, deps.sh, enginerpc/enginerpc.cc, enginerpc/enginerpc.hh, inc/com/centreon/engine/globals.hh, modules/external_commands/inc/com/centreon/engine/modules/external_commands/utils.hh, modules/external_commands/src/utils.cc, src/globals.cc
No more pthread in engine. Just std::threads... The goal is to remove pthread_cancel() calls, not compatible with c++14.
REFS: MON-10682
=> Mon 10682 minimal

deps.sh, enginerpc/enginerpc.cc, inc/com/centreon/engine/common.hh, inc/com/centreon/engine/enginerpc.hh, inc/com/centreon/engine/globals.hh, modules/external_commands/inc/com/centreon/engine/modules/external_commands/utils.hh, modules/external_commands/src/utils.cc, src/globals.cc, tests/enginerpc/enginerpc.cc
The segfault during centengine stop is fixed.
REFS: MON-10682
=> Mon 10682 engine segfault 21.10

Jenkinsfile
Because of : 
- the new branch workflow
- the new packaging and rpm pushing workflow
- the necessity to give an easy access to rpm for the QA
Here's an enhancement that : 
- specify "QA" branches that are develop and dev-xx.yy.zz to manage the rpm pushing location 
- //lise build tests and packaging for all distributions
- push rpm directly on yum.centreon.com
It means that RPM created from develop and dev-xx.yy.zz branches are pushed directly to the unstable repo of yum.centreon.com and RPM created from release branches are pushed directly to the testing repo. 
No more RPM pushing for reference branches (for now) and PR- / CI branches
It speeds up the pipeline and the feedback loop for devs also.
Launch a job of each type of branches and …
=> enh(ci): new packaging workflow

Jenkinsfile
Fixes the double rpm delivery in the yum repository
Launch develop pipeline and check if there is twice the same rpm in the unstable engine repo
=> fix(ci): delete rpm after stashing

src/host.cc, src/service.cc, tests/notifications/host_flapping_notification.cc, tests/notifications/service_flapping_notification.cc
=> fix(flapping): don't start flapping with parent not up
